/**
 * Bloom & Bliss - Master Products Database
 * Contains realistic flowers, gifts, combos, and occasion tags.
 * Formatted with Indian Rupees (₹), high quality images, and fallback handlers.
 */

const PRODUCTS = [
  // ===================== FLOWERS (14 Products) =====================
  {
    id: "fl-1",
    name: "Classic Red Rose Bouquet",
    category: "flowers",
    subCategory: "roses",
    occasions: ["valentines", "anniversary", "birthday"],
    price: 1499,
    originalPrice: 1899,
    rating: 4.9,
    reviewsCount: 328,
    badge: "Bestseller",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW0xvmwALQJJ0CQVgj6uG7ptvso_Cgq6xwcoB82HQpHg&s",
    shortDesc: "12 premium long-stem Dutch red roses wrapped in blush craft paper.",
    description: "Handcrafted with the freshest velvety red Dutch roses, accented with dainty baby's breath and wrapped in luxurious dual-tone pink and craft paper with a satin ribbon bow. Perfect for romantic confessions, anniversaries, and heartfelt surprises.",
    features: ["12 Fresh Dutch Red Roses", "Wrapped in Dual-Tone Kraft & Blush Paper", "Includes Floral Food Sachet", "Free Personalized Message Card"]
  },
  {
    id: "fl-2",
    name: "Pink Rose Basket of Grace",
    category: "flowers",
    subCategory: "roses",
    occasions: ["birthday", "anniversary", "thank-you", "congratulations"],
    price: 1799,
    originalPrice: 2199,
    rating: 4.8,
    reviewsCount: 214,
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=800&q=80",
    shortDesc: "20 delicate blush pink roses arranged in a woven willow basket.",
    description: "An ethereal arrangement of 20 freshly plucked pastel pink roses nestled in a rustic woven wicker basket with eucalyptus greens and pearl-tipped pins.",
    features: ["20 Fresh Pink Roses", "Rustic Woven Willow Handle Basket", "Hydrated Floral Foam Base", "Free Personalized Message Card"]
  },
  {
    id: "fl-3",
    name: "Sunshine Flower Bouquet",
    category: "flowers",
    subCategory: "bouquets",
    occasions: ["friendship", "get-well-soon", "congratulations", "birthday"],
    price: 1299,
    originalPrice: 1599,
    rating: 4.9,
    reviewsCount: 182,
    badge: "Popular",
    image: "https://assets.winni.in/c_limit,dpr_1,fl_progressive,q_80,w_1000/89612_sunshine-sunflower-bouquet.jpeg",
    shortDesc: "Vibrant golden sunflowers and seasonal daisies to brighten any day.",
    description: "Bursting with warmth and positive energy, this bouquet features golden sunflowers, yellow chrysanthemums, and fresh seasonal foliage hand-tied with rustic jute twine.",
    features: ["3 Jumbo Golden Sunflowers", "Yellow Button Daisies & Greenery", "Eco-friendly Jute Tie Wrap", "Same-Day Fresh Delivery"]
  },
  {
    id: "fl-4",
    name: "Elegant White Lily Bouquet",
    category: "flowers",
    subCategory: "lilies",
    occasions: ["wedding", "anniversary", "thank-you", "congratulations"],
    price: 1899,
    originalPrice: 2399,
    rating: 4.9,
    reviewsCount: 165,
    badge: "Premium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwjh8SLGRBmMyFGhbdkqHEU-mFbGptQWA4s0mnnEBxWA&s=10",
    shortDesc: "Fragrant oriental white lilies paired with gypsophila.",
    description: "Symbolizing purity and timeless devotion, these blooming oriental white lilies fill any room with a sweet calming fragrance. Wrapped in frosted white packaging with silver accents.",
    features: ["6 Stems Multi-Bloom Oriental Lilies", "Dainty White Gypsophila Fillers", "Water-Pack Stems for Freshness", "Signature Silver Ribbon"]
  },
  {
    id: "fl-5",
    name: "Royal Purple Orchid Vase",
    category: "flowers",
    subCategory: "orchids",
    occasions: ["congratulations", "festivals", "anniversary", "thank-you"],
    price: 1999,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 140,
    badge: "Luxury",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwjh8SLGRBmMyFGhbdkqHEU-mFbGptQWA4s0mnnEBxWA&s=10",
    shortDesc: "Exotic purple Dendrobium orchids set in a fluted glass vase.",
    description: "Exotic, long-lasting Dendrobium orchids arranged gracefully inside a designer fluted glass vase. A symbol of luxury, rare beauty, and thoughtful admiration.",
    features: ["10 Fresh Purple Orchid Stems", "Included Designer Glass Vase", "Lasts 7 to 10 Days Indoors", "Ready to Display on Delivery"]
  },
  {
    id: "fl-6",
    name: "Blush Peony & Hydrangea Dream",
    category: "flowers",
    subCategory: "bouquets",
    occasions: ["wedding", "anniversary", "birthday"],
    price: 2499,
    originalPrice: 2999,
    rating: 5.0,
    reviewsCount: 97,
    badge: "Editor's Pick",
    image: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Opulent blush peonies and sky-blue hydrangeas in pastel wrap.",
    description: "A high-fashion European style arrangement combining lush pink peony blooms, soft sky-blue hydrangeas, spray roses, and silver dollar eucalyptus.",
    features: ["Imported Peonies & Hydrangeas", "Silver Dollar Eucalyptus Greens", "Triple-Layered Luxury Wrap", "Free Flower Food Sachet"]
  },
  {
    id: "fl-7",
    name: "Pastel Carnation Harmony",
    category: "flowers",
    subCategory: "carnations",
    occasions: ["thank-you", "get-well-soon", "friendship", "birthday"],
    price: 1199,
    originalPrice: 1499,
    rating: 4.7,
    reviewsCount: 153,
    badge: "Special Offer",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQCOIRepsoVC3MIT7pNuvhFqt-NMH_d77Og7TN5O5Z5g&s=10",
    shortDesc: "15 ruffled carnations in peach, powder pink, and cream tones.",
    description: "Long-lasting ruffled carnations in delicate ombré pastel tones. Hand-tied in a lavender matte paper wrap, ideal for heartfelt expressions of gratitude and warmth.",
    features: ["15 Pastel Carnation Stems", "Lavender Matte Gift Wrap", "Long Vase Life (up to 9 days)", "Care Instructions Card"]
  },
  {
    id: "fl-8",
    name: "Lavender Mist Dutch Tulips",
    category: "flowers",
    subCategory: "tulips",
    occasions: ["birthday", "anniversary", "friendship", "congratulations"],
    price: 2199,
    originalPrice: 2699,
    rating: 4.9,
    reviewsCount: 112,
    badge: "Imported",
    image: "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Freshly imported lilac and violet Dutch tulips in minimal wrap.",
    description: "Directly sourced from the fields of Holland, these crisp, cup-shaped lilac tulips celebrate understated sophistication and spring wonder.",
    features: ["10 Imported Dutch Tulips", "Minimalist Eco Paper Sleeving", "Opens Beautifully Over 48h", "Chilled Temperature Delivery"]
  },
  {
    id: "fl-9",
    name: "Sunset Glow Mixed Gerberas",
    category: "flowers",
    subCategory: "gerberas",
    occasions: ["birthday", "friendship", "get-well-soon", "congratulations"],
    price: 1099,
    originalPrice: 1399,
    rating: 4.6,
    reviewsCount: 189,
    badge: "Value Buy",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStECZMkx-fJsK9njaN91xxvRqQdao3GehChrCAJ0xxsg&s=10",
    shortDesc: "Bright red, orange, and golden yellow gerbera daisies.",
    description: "A cheerful kaleidoscope of colorful gerbera daisies bundled with fresh greens to spark instant smiles and lively celebrations.",
    features: ["12 Vibrant Multicolor Gerberas", "Green Foliage Accents", "Glossy Ribbon Tie", "Fresh Pick Guarantee"]
  },
  {
    id: "fl-10",
    name: "Pure Serenity White Roses",
    category: "flowers",
    subCategory: "roses",
    occasions: ["wedding", "congratulations", "thank-you", "anniversary"],
    price: 1599,
    originalPrice: 1999,
    rating: 4.8,
    reviewsCount: 134,
    badge: "New",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJJCzRpoabV43V3gF4xXISJV2VJ0I1kDANIPPF-LeavQ&s=10",
    shortDesc: "16 pristine white roses wrapped in organza silk ribbon.",
    description: "Classic ivory white roses radiating peaceful elegance, innocence, and sincerity. Wrapped in frosty white cellophane with an iridescent silk bow.",
    features: ["16 Crisp White Stem Roses", "Translucent Organza Fabric Wrap", "Long-Lasting Buds", "Free Gift Message Note"]
  },
  {
    id: "fl-11",
    name: "Celestial Blue Hydrangea Bunch",
    category: "flowers",
    subCategory: "bouquets",
    occasions: ["anniversary", "thank-you", "friendship", "birthday"],
    price: 1799,
    originalPrice: 2199,
    rating: 4.9,
    reviewsCount: 88,
    badge: "Exclusive",
    image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Lush cloud-like blue hydrangeas paired with baby breath.",
    description: "Dramatic, cloud-like sky blue hydrangeas nestled with dainty white gypsophila and tied with deep navy satin ribbon.",
    features: ["3 Giant Blue Hydrangea Blooms", "Plentiful White Gypsophila", "Water Sponge Wrapped Base", "Signature Bloom Box packaging"]
  },
  {
    id: "fl-12",
    name: "Velvet Crimson Romance Box",
    category: "flowers",
    subCategory: "roses",
    occasions: ["valentines", "anniversary", "birthday"],
    price: 2299,
    originalPrice: 2799,
    rating: 5.0,
    reviewsCount: 276,
    badge: "Bestseller",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9uVzfbDzTBhz-ha3I7ueyRZ0ddS3pFWhALK1jYSoZzA&s",
    shortDesc: "24 deep red roses set in a round luxury Parisian hatbox.",
    description: "The pinnacle of romantic gifting. Two dozen premium red roses meticulously set in a handcrafted black velvet keepsake hatbox with gold foil Bloom & Bliss embossing.",
    features: ["24 Hand-Arranged Roses", "Re-usable Velvet Parisian Hatbox", "Foam Oasis Base for Long Hydration", "Premium Keepsake Box"]
  },
  {
    id: "fl-13",
    name: "Golden Radiance Sunflower Basket",
    category: "flowers",
    subCategory: "sunflowers",
    occasions: ["get-well-soon", "friendship", "festivals", "birthday"],
    price: 1699,
    originalPrice: 2099,
    rating: 4.8,
    reviewsCount: 94,
    badge: null,
    image:" https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStsD1_uvwqlfC6yFjbXAWY6vMomzyX7hzzL_ZVdRtR9Q&s=10",
    shortDesc: "Cheerful sunflowers & chamomile blooms in a bamboo basket.",
    description: "A countryside-inspired basket arrangement featuring sunny bloom heads, chamomile daisies, and fragrant herbs.",
    features: ["5 Sunflowers + Chamomile", "Natural Bamboo Woven Basket", "Bright & Uplifting Aesthetic", "Same Day Express Delivery"]
  },
  {
    id: "fl-14",
    name: "Graceful Pink Asiatic Lilies",
    category: "flowers",
    subCategory: "lilies",
    occasions: ["birthday", "anniversary", "wedding", "festivals"],
    price: 1749,
    originalPrice: 2149,
    rating: 4.7,
    reviewsCount: 104,
    badge: null,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRdlfM8dpOup2rRjlk9LkVLM3tuGzb1578Q9x7UKIYlg&s=10",
    shortDesc: "Star-shaped pink Asiatic lilies with eucalyptus.",
    description: "Captivating candy-pink Asiatic lilies with striking recurved petals and lush eucalyptus, wrapped in pastel lilac kraft paper.",
    features: ["5 Stems Asiatic Lilies (15+ buds)", "Blush Eucalyptus Foliage", "Long lasting blooms", "Free Care Guide"]
  },

  // ===================== GIFTS (14 Products) =====================
  {
    id: "gf-1",
    name: "Personalized Engraved Photo Frame",
    category: "gifts",
    subCategory: "personalized",
    occasions: ["anniversary", "birthday", "wedding", "friendship"],
    price: 899,
    originalPrice: 1299,
    rating: 4.9,
    reviewsCount: 340,
    badge: "Bestseller",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Handcrafted pine wood frame customized with your photo and names.",
    description: "Custom engraved with your names, special date, and personal message on premium natural pine wood. Glass front with brass corner rivets.",
    features: ["Custom Laser Engraving Included", "High-Definition Photo Print", "Solid Pine Wood Construction", "Desk Stand & Wall Mount Hook"]
  },
  {
    id: "gf-2",
    name: "Artisanal Belgian Chocolate Box 16pc",
    category: "gifts",
    subCategory: "chocolates",
    occasions: ["festivals", "birthday", "anniversary", "valentines"],
    price: 1099,
    originalPrice: 1399,
    rating: 4.9,
    reviewsCount: 412,
    badge: "Bestseller",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Handmade gourmet truffles, praline, and dark sea-salt ganache.",
    description: "16 exquisite artisanal chocolates made with single-origin Belgian cocoa, hazelnut crunch, salted caramel, and raspberry ganache in a rigid gold-stamped box.",
    features: ["16 Handcrafted Belgian Truffles", "100% Vegetarian (Eggless)", "Gold Foil Embossed Box", "Insulated Cold-Pack Packaging"]
  },
  {
    id: "gf-3",
    name: "Fluffy Cuddle Teddy Bear 12-Inch",
    category: "gifts",
    subCategory: "soft-toys",
    occasions: ["birthday", "valentines", "get-well-soon", "friendship"],
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviewsCount: 220,
    badge: "Customer Favorite",
    image: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Ultra-soft plush teddy bear with a stylish satin neck bow.",
    description: "Crafted with cloud-soft fur and weighted paws, this adorable mocha-brown teddy bear wears a satin red bowtie and is hug-tested for ultimate comfort.",
    features: ["12-inch Huggable Height", "Ultra-Plush Hypoallergenic Fur", "Embroidered Paw Accents", "Safe for All Ages"]
  },
  {
    id: "gf-4",
    name: "Luxury Botanical Spa Hamper",
    category: "gifts",
    subCategory: "gift-hampers",
    occasions: ["birthday", "get-well-soon", "thank-you", "festivals"],
    price: 2199,
    originalPrice: 2799,
    rating: 5.0,
    reviewsCount: 178,
    badge: "Luxury",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Organic lavender scrub, bath salts, shea butter & aroma candle.",
    description: "A therapeutic self-care ritual box featuring lavender bath salts, hand-poured soy candle, cold-pressed olive soap, organic body butter, and a waffle spa towel in a wooden keepsake caddy.",
    features: ["100% Natural Organic Ingredients", "Handcrafted Soy Wax Candle (120g)", "Lavender Exfoliating Bath Salts", "Handmade Pine Wooden Tray"]
  },
  {
    id: "gf-5",
    name: "Mini Jade Bonsai in Ceramic Pot",
    category: "gifts",
    subCategory: "plants",
    occasions: ["congratulations", "friendship", "thank-you", "festivals"],
    price: 699,
    originalPrice: 899,
    rating: 4.8,
    reviewsCount: 195,
    badge: "Eco-Friendly",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Low-maintenance air-purifying succulent bringing good luck & wealth.",
    description: "Considered an auspicious plant that invites wealth and fortune. Placed in a minimalist matte-white handcrafted ceramic planter with drainage tray.",
    features: ["Thriving 3-Year Old Jade Plant", "Handcrafted Matte Ceramic Pot", "Low Watering (Once a week)", "Purifies Indoor Air"]
  },
  {
    id: "gf-6",
    name: "Aroma Soy Scented Candle Trio",
    category: "gifts",
    subCategory: "home-decor",
    occasions: ["anniversary", "birthday", "festivals", "wedding"],
    price: 999,
    originalPrice: 1299,
    rating: 4.9,
    reviewsCount: 167,
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Trio of French lavender, Madagascar vanilla & sandalwood candles.",
    description: "100% natural soy wax candles with lead-free cotton wicks, offering up to 45 hours of soothing aromatic burn time in amber glass jars.",
    features: ["Set of 3 Fragrance Jars (100g each)", "Lead-Free 100% Cotton Wicks", "Smokeless Clean Burn", "Gold Metal Lid Tops"]
  },
  {
    id: "gf-7",
    name: "Gourmet Dry Fruit & Honey Hamper",
    category: "gifts",
    subCategory: "gift-hampers",
    occasions: ["festivals", "wedding", "congratulations", "thank-you"],
    price: 1899,
    originalPrice: 2399,
    rating: 4.8,
    reviewsCount: 142,
    badge: "Festive",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Roasted almonds, cashews, Afghani raisins & wild forest honey jar.",
    description: "A regal gift hamper featuring premium jumbo Californian almonds, W240 cashews, walnut kernels, and wild forest honey jars in a laser-cut royal motif box.",
    features: ["Californian Almonds & W240 Cashews (200g each)", "Afghani Green Raisins (150g)", "Raw Organic Forest Honey (120g)", "Festive Keepsake Box"]
  },
  {
    id: "gf-8",
    name: "Customized Spotify Acrylic Music Plaque",
    category: "gifts",
    subCategory: "personalized",
    occasions: ["anniversary", "birthday", "valentines", "friendship"],
    price: 949,
    originalPrice: 1399,
    rating: 4.9,
    reviewsCount: 310,
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Shatterproof acrylic plaque with your song, scannable code & photo.",
    description: "Freeze your anthem in time! Features high-definition UV printing on shatterproof acrylic with a warm LED wooden stand that glows beautifully at night.",
    features: ["Scannable Spotify Code", "Warm White LED Wooden Stand Included", "HD UV Anti-Scratch Print", "USB Powered LED"]
  },
  {
    id: "gf-9",
    name: "Assorted French Macarons Box 12pc",
    category: "gifts",
    subCategory: "chocolates",
    occasions: ["birthday", "anniversary", "wedding", "festivals"],
    price: 1199,
    originalPrice: 1499,
    rating: 4.7,
    reviewsCount: 128,
    badge: "Gourmet",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Pistachio, rose, salted caramel, berry & chocolate macarons.",
    description: "Authentic Parisian macarons baked with almond flour and rich buttercream fillings in rainbow pastel colors. Delivered temperature-controlled.",
    features: ["12 Assorted Macarons", "Pastel Gift Box with Bow", "100% Gluten-Friendly Recipe", "Temperature-Safe Courier Box"]
  },
  {
    id: "gf-10",
    name: "Dust-Pink Velvet Jewelry Organizer",
    category: "gifts",
    subCategory: "accessories",
    occasions: ["birthday", "wedding", "anniversary"],
    price: 1299,
    originalPrice: 1699,
    rating: 4.8,
    reviewsCount: 115,
    badge: "New",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Plush velvet multi-compartment travel jewelry organizer box.",
    description: "Compact dual-layer jewelry case with necklace hooks, ring rolls, and adjustable dividers lined in anti-tarnish velvet with a gold zipper.",
    features: ["Dual Tier Organized Layout", "Anti-Tarnish Velvet Lining", "Compact Travel Friendly Size", "Smooth Gold Metal Zipper"]
  },
  {
    id: "gf-11",
    name: "Lucky 3-Tier Bamboo Plant",
    category: "gifts",
    subCategory: "plants",
    occasions: ["congratulations", "get-well-soon", "festivals", "friendship"],
    price: 599,
    originalPrice: 799,
    rating: 4.6,
    reviewsCount: 240,
    badge: "Best Value",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Braided lucky bamboo in a glass bowl with smooth river pebbles.",
    description: "A revered symbol of health, happiness, and peace in Feng Shui. Requires just fresh water and indirect sunlight to flourish.",
    features: ["3-Tier Live Bamboo Stalks", "Included Clear Glass Bowl", "Natural Polished River Pebbles", "Feng Shui Blessed Plant"]
  },
  {
    id: "gf-12",
    name: "24K Gold Plated Forever Rose",
    category: "gifts",
    subCategory: "accessories",
    occasions: ["valentines", "anniversary", "wedding"],
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 185,
    badge: "Everlasting",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRi1-nUA5VrIe51928Lyo52zvqpcqAKE8acFU9xMWplw&s=10",
    shortDesc: "Preserved natural rose dipped in 24k gold foil in an acrylic case.",
    description: "A real rose dipped in 24K gold foil that will never fade or wither, symbolizing everlasting love and cherished memories.",
    features: ["Authentic 24K Gold Plating Certificate", "Clear Acrylic Moon Stand", "Padded Luxury Gift Box", "Never Withers or Fades"]
  },
  {
    id: "gf-13",
    name: "Belgian Chocolate Truffle Cake 500g",
    category: "gifts",
    subCategory: "cakes",
    occasions: ["birthday", "anniversary", "congratulations"],
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviewsCount: 389,
    badge: "Fresh Bakes",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Eggless rich chocolate sponge layered with smooth dark ganache.",
    description: "Freshly baked eggless cake layered with decadent 55% cocoa ganache, chocolate curls, and customizable birthday topper.",
    features: ["500g Eggless Freshly Baked", "Rich Belgian 55% Cocoa Truffle", "Includes Candle & Knife Set", "Same-Day 2hr Express Delivery"]
  },
  {
    id: "gf-14",
    name: "Nordic Ceramic Donut Vase & Pampas",
    category: "gifts",
    subCategory: "home-decor",
    occasions: ["wedding", "congratulations", "festivals", "thank-you"],
    price: 1399,
    originalPrice: 1799,
    rating: 4.8,
    reviewsCount: 82,
    badge: "Aesthetic",
    image: "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Textured ceramic donut vase with fluffy dried natural pampas grass.",
    description: "Nordic aesthetic ceramic vase bundled with natural sun-dried pampas grass stems, creating an elegant boho centerpiece for living spaces.",
    features: ["Matte Terracotta Finished Ceramic", "6 Fluffy Dried Pampas Grass Stems", "No Water or Maintenance Needed", "Instagram-Worthy Home Decor"]
  },

  // ===================== COMBOS (8 Products) =====================
  {
    id: "cb-1",
    name: "Roses + Belgian Chocolates Delight",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["valentines", "anniversary", "birthday"],
    price: 2399,
    originalPrice: 2999,
    rating: 4.9,
    reviewsCount: 410,
    badge: "Bestseller",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0zbyI3gMas4OOjfxl8JZagMZSxpLitjddMrxHQFYIsA&s",
    shortDesc: "12 red roses bouquet paired with 16pc handcrafted chocolate box.",
    description: "The classic romantic pairing: a hand-tied bouquet of fresh crimson roses together with our finest Belgian dark and hazelnut chocolate assortment.",
    features: ["12 Dutch Red Roses Bouquet", "16pc Belgian Chocolate Box", "Silk Bow Ribbon Wrap", "Personalized Love Note"]
  },
  {
    id: "cb-2",
    name: "Flowers + Cuddle Teddy Romance Combo",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["valentines", "birthday", "friendship"],
    price: 1999,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 298,
    badge: "Sweet Surprise",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdaxdIwqESjUddUP9MAWWbOrkj_C34RUuCcHLgnuPyxQ&s=10",
    shortDesc: "Blush pink roses bunch bundled with a 12-inch fluffy teddy bear.",
    description: "Warm hearts with this sweet combo of garden-fresh pink roses, gypsophila fillers, and a super snuggly mocha plush teddy bear with a custom greeting card.",
    features: ["10 Fresh Pink Roses", "12-Inch Plush Huggable Teddy", "Soft Pastel Tissue & Bow", "Express Doorstep Delivery"]
  },
  {
    id: "cb-3",
    name: "Birthday Bliss Grand Celebration Hamper",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["birthday"],
    price: 2899,
    originalPrice: 3499,
    rating: 5.0,
    reviewsCount: 320,
    badge: "All-in-One",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXMp42cA3npnRWy_QW2pxflsdw3OLhFW9VtkENqzXueQ&s=10",
    shortDesc: "Mixed flower bouquet, 500g chocolate cake, party balloons & card.",
    description: "The ultimate birthday in a box! Fresh pastel flower bouquet, Belgian chocolate truffle cake, festive party candle, and hand-written gold greeting card.",
    features: ["Fresh Flower Bouquet (Roses & Lilies)", "500g Belgian Truffle Cake (Eggless)", "Set of 5 Pastel Chrome Balloons", "Golden Birthday Cake Topper"]
  },
  {
    id: "cb-4",
    name: "Anniversary Golden Elegance Combo",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["anniversary", "wedding"],
    price: 3299,
    originalPrice: 3999,
    rating: 4.9,
    reviewsCount: 165,
    badge: "Premium",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDFIgewC5TMyXhP8Ki03MOI7kCqFu9OPbAUmcSW0F1xQ&s=10",
    shortDesc: "Oriental lilies bouquet + aroma soy candle + customized acrylic plaque.",
    description: "Celebrate milestones with fragrant white oriental lilies, a calming vanilla amber soy candle, and a personalized acrylic keepsake plaque engraved with your names.",
    features: ["Fresh White Oriental Lilies Bunch", "French Vanilla Soy Candle Jar (200g)", "Custom Engraved Acrylic Plaque", "Presented in Bloom & Bliss Trunk Box"]
  },
  {
    id: "cb-5",
    name: "Luxury Self-Care & Floral Bloom Box",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["birthday", "thank-you", "get-well-soon"],
    price: 2799,
    originalPrice: 3399,
    rating: 4.9,
    reviewsCount: 144,
    badge: "Pamper Box",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqU4IfwGPjSvF21dSbgdZGTk5R-XwoJwIVsJqH7k8-pA&s=10",
    shortDesc: "Lavender & peony posy, organic bath salts, body butter & herbal tea.",
    description: "Pure relaxation delivered in a ribbon-tied gift box. Featuring botanical pamper essentials paired with a fresh mini floral posy.",
    features: ["Fresh Mini Lavender Posy", "Organic Epsom Bath Salts Jar", "Whipped Shea Body Butter (100g)", "Pyramid Chamomile Herbal Tea (10 bags)"]
  },
  {
    id: "cb-6",
    name: "Sweet Surprises Trio (Bouquet + Teddy + Ferrero)",
    category: "combos",
    subCategory: "gift-hampers",
    occasions: ["valentines", "birthday", "anniversary"],
    price: 2499,
    originalPrice: 3099,
    rating: 4.9,
    reviewsCount: 275,
    badge: "Bestseller",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaOLZ-8US-qrTf1Wu2zmA3rhPoLvcubZdC94Vv2MKgWA&s=10",
    shortDesc: "10 red roses, 16pc Ferrero Rocher box & plush mini teddy.",
    description: "Triple the delight with velvety red roses, crisp Italian hazelnut Ferrero Rocher chocolates, and a soft huggable teddy.",
    features: ["10 Fresh Dutch Red Roses", "Ferrero Rocher Box 16pc", "6-inch Mini Plush Teddy", "Golden Ribbon Packaging"]
  },
  {
    id: "cb-7",
    name: "Morning Fresh Plant & Tea Gift Set",
    category: "combos",
    subCategory: "plants",
    occasions: ["thank-you", "congratulations", "friendship", "get-well-soon"],
    price: 1699,
    originalPrice: 2099,
    rating: 4.7,
    reviewsCount: 96,
    badge: "Wellness",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDACi9_psRpPoep1BGeVIYbIEdUoikLKx0qzYgX5A_Ng&s",
    shortDesc: "Potted Jade plant + Chamomile organic herbal tea canister + ceramic mug.",
    description: "Inspire morning calm and clarity with a hardy desk Jade succulent, organic loose chamomile blossoms in a tin, and a handcrafted pottery coffee mug.",
    features: ["Thriving Desk Jade Bonsai in Pot", "Organic Loose Chamomile Blossom Tin", "Ceramic Artisan Coffee Mug", "Mindfulness Guide Bookmark"]
  },
  {
    id: "cb-8",
    name: "Royal Orchid & Belgian Treats Box",
    category: "combos",
    subCategory: "orchids",
    occasions: ["festivals", "wedding", "congratulations"],
    price: 2599,
    originalPrice: 3199,
    rating: 4.8,
    reviewsCount: 110,
    badge: "Festive Pick",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc7a7pfTMRTNdWy6ftZKTNH3B2c9fp9kp3LPRzxHT5FQ&s=10",
    shortDesc: "Purple orchids bunch paired with 12 handcrafted artisanal chocolates.",
    description: "A regal combination of exotic Dendrobium orchids and assorted Belgian pralines in an embossed pastel gift presentation.",
    features: ["8 Stems Purple Dendrobium Orchids", "12 Artisanal Belgian Pralines", "Luxury Embossed Hamper Box", "Free Hand-Calligraphed Note"]
  }
];

// Helper functions for products querying
const ProductStore = {
  getAll: () => PRODUCTS,
  getById: (id) => PRODUCTS.find(p => p.id === id),
  getByCategory: (category) => PRODUCTS.filter(p => p.category === category),
  getByOccasion: (occ) => PRODUCTS.filter(p => p.occasions && p.occasions.includes(occ.toLowerCase())),
  getFeatured: () => PRODUCTS.filter(p => ["fl-1", "fl-2", "fl-3", "fl-4", "cb-2", "cb-1", "gf-1", "cb-3", "gf-4", "gf-5"].includes(p.id)),
  getBestSellers: () => PRODUCTS.filter(p => p.badge === "Bestseller" || p.rating >= 4.9).slice(0, 8),
  getCombos: () => PRODUCTS.filter(p => p.category === "combos"),
  search: (query) => {
    if (!query || !query.trim()) return PRODUCTS;
    const q = query.toLowerCase().trim();
    return PRODUCTS.filter(p => 
      p.name.toLowerCase().includes(q) ||
      p.shortDesc.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.subCategory.toLowerCase().includes(q) ||
      (p.occasions && p.occasions.some(occ => occ.toLowerCase().includes(q)))
    );
  }
};

// Export to window
window.PRODUCTS = PRODUCTS;
window.ProductStore = ProductStore;
